binary_sensor:
  - platform: template
    sensors:
      test_door_contact_mounted:
        friendly_name: "Test Door Contact Mounted"
        device_class: door
        value_template: "{{ is_state('input_boolean.test_door_contact_mounted', 'on') }}"
  - platform: template
    sensors:
      test_garage_contact_mounted:
        friendly_name: "Test garage Contact Mounted"
        device_class: garage_door
        value_template: "{{ is_state('input_boolean.test_door_contact_mounted', 'on') }}"

input_boolean:
  test_door_contact_mounted:
    name: "Door Contact Mounted"
    initial: off
